services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_RECAPTCHA_SITE_KEY=${NEXT_PUBLIC_RECAPTCHA_SITE_KEY}
        - NEXT_PUBLIC_TURNSTILE_SITE_KEY=${NEXT_PUBLIC_TURNSTILE_SITE_KEY}
    restart: always
    ports:
      - "3000:3000"
    env_file: .env # Use the main .env for secrets
    environment:
      # Mandatory overrides for the Docker ecosystem
      NODE_ENV: production
      DATABASE_URL: postgresql://postgres:password@postgres:5432/ticketing?schema=public
      REDIS_URL: redis://redis:6379
      SMTP_HOST: mailpit
      SMTP_PORT: 1025
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      mailpit:
        condition: service_started
    volumes:
      - ./public/uploads:/app/public/uploads

  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ticketing
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ticketing"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  mailpit:
    image: axllent/mailpit
    restart: always
    ports:
      - "8025:8025" # Web UI
      - "1025:1025" # SMTP Port

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"

  npm:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'      # Pintu masuk HTTP Publik
      - '81:81'      # Pintu masuk Dashboard Admin NPM
      - '443:443'    # Pintu masuk HTTPS Publik
    volumes:
      - ./npm/data:/data
      - ./npm/letsencrypt:/etc/letsencrypt

volumes:
  postgres_data:
  redis_data:
