name: CI/CD Manual Local

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted  # Pastikan ini sesuai dengan label saat config tadi
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        # Step checkout ini akan mendownload kode terbaru ke folder 'work' milik runner

      - name: Rebuild Docker Services
        run: |
          # Pindah ke folder project utamamu (sesuaikan path-nya)
          cd /home/ucupsarucup/ticketing/myaspirasi-bpptik 
          git pull origin main
          docker-compose -f docker-compose.prod.yml up -d --build